### ISSUE TITLE
Сообщить данные для получения сертификата финалиста

### ISSUE THREAD

**Issue by alehinsasha** [AleksandrAkhunov/work4#11]
В комментарии к этому issue напишите ваши:
- Имя
- Фамилию
- Адрес электронной почты, на которую выслать сертификат

**Comment by AleksandrAkhunov** [comment]
Александр 
Ахунов
alexandr.ahunov@rial-soft.ru

**Comment by alehinsasha** [comment]
Письмо с поздравлением и сертификатом отправлено! Получили?

**Comment by AleksandrAkhunov** [comment]
Да, спасибо. Получил
