### ISSUE TITLE
Вынести процедуру удаления документов в отдельный шаг

### ISSUE THREAD

**Issue by alehinsasha** [AleksandrAkhunov/work4#2]
В каталоге feature создайте каталог и в нем создайте фичу в которой собирайте шаги которые будете использовать в других ваших фичах, так вы научитесь формировать свою библиотеку шагов. Начните с [этой ](https://github.com/AleksandrAkhunov/work4/blob/master/src/features/step_definitions/%D0%A0%D0%B5%D0%B0%D0%BB%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%8F%D0%A2%D0%BE%D0%B2%D0%B0%D1%80%D0%BE%D0%B2/Form/%D0%A4%D0%BE%D1%80%D0%BC%D0%B0/%D0%A4%D0%BE%D1%80%D0%BC%D0%B0.bsl#L192) процедуры.

**Comment by AleksandrAkhunov** [comment]
1) Как должна выглядеть такая фича ? Обычно они тестируют поведение.
2) Как из своей фичи вызывать процедуру этой фичи ?

**Comment by alehinsasha** [comment]
> 1) Как должна выглядеть такая фича ? Обычно они тестируют поведение.

Это будет служебная фича, она должна лежать в отдельном каталоге и путь к этому каталогу должен быть указан в vanessa-behavior на закладке "Библиотеки". На одном из текущих проектов моя библиотечная фича выглядит так:

```
# encoding: utf-8
# language: ru

Функционал: Библиотека шагов
    Как разработчик
    Хочу иметь библиотеку универсальных шагов
    Чтобы вести разработку конфигурации

Контекст:
#   Дано Я открыл новый сеанс TestClient или подключил уже существующий

Сценарий: Универсальные шаги
    И не открылось окно с текстом "Текст"
    И я закрываю клиент тестирования
    И я удаляю все документы вида "СделкаСКлиентом"
    И я загружаю данные для сценария из макета "Сделки"

```

> 2) Как из своей фичи вызывать процедуру этой фичи ?

Чтобы в одной фиче использовать шаги из другой фичи, нужно чтобы определение шага, т.е. сам текст был одинаковый. Ну и в библиотеки нужно добавить.

**Comment by AleksandrAkhunov** [comment]
сделал библиотеку. Вставил вызов

**Comment by AleksandrAkhunov** [comment]
в фичу реализациятоваров и отчетопродажах

**Comment by alehinsasha** [comment]
В фичах "реализациятоваров" и "отчетопродажах" после загрузки в vanessa-behavior строка с шагом должна выделяться серым. Есть такое дело?

**Comment by AleksandrAkhunov** [comment]
да
