### ISSUE TITLE
Научиться работать с функциональностью "Автоватизированное тестирование" из vanessa-behavior

### ISSUE THREAD

**Issue by alehinsasha** [AleksandrAkhunov/work4#3]
В учебных целях, создайте фичу которая:
- если нет элемента справочника с наименованием "контрагент2", создает элемент с таким наименованием, а потом переименовывает его в "контрагент1"
- если элементов справочника с наименованием "контрагент1" больше 3, то удаляет все элементы с таким наименованием.

**Comment by AleksandrAkhunov** [comment]
реализовал фичу
